function y = Filtering(x)
%FILTERING Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 13-Jan-2021 02:01:34

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Bandpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 22050;  % Sampling Frequency
    %
    % N    = 40;       % Order
    % Fc1  = 300;      % First Cutoff Frequency
    % Fc2  = 3400;     % Second Cutoff Frequency
    % flag = 'scale';  % Sampling Flag
    % Beta = 0;        % Window Parameter
    % % Create the window vector for the design algorithm.
    % win = kaiser(N+1, Beta);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.00718542440492662 -0.0221346817180771 ...
        -0.0325500582802864 -0.0292079582614392 -0.0142727923790801 ...
        -0.000704141011790946 -0.00191375121813385 -0.0196865763820792 ...
        -0.0408680879169082 -0.046946744803771 -0.0299344533700261 ...
        -0.00155500115853875 0.0133767223962624 -0.00358391215794917 ...
        -0.0463881777105584 -0.0829222100626418 -0.0740960726881511 ...
        -0.00203775220755329 0.112556837282362 0.217897716757523 ...
        0.260514528097308 0.217897716757523 0.112556837282362 ...
        -0.00203775220755329 -0.0740960726881511 -0.0829222100626418 ...
        -0.0463881777105584 -0.00358391215794917 0.0133767223962624 ...
        -0.00155500115853875 -0.0299344533700261 -0.046946744803771 ...
        -0.0408680879169082 -0.0196865763820792 -0.00191375121813385 ...
        -0.000704141011790946 -0.0142727923790801 -0.0292079582614392 ...
        -0.0325500582802864 -0.0221346817180771 -0.00718542440492662]);
end

y = step(Hd,double(x));


% [EOF]
